settings:
 config_version: 4.6
 check_update_on_join: true
 sign_line: '[SellChest]'
 prefix: '&7[&aSell&eChest&7]&r '

itemsold:
- IRON_INGOT:10.00
- LOG:1:50.50

blacklist:
- CHEST

signmessage:
- '&7[&cSellChest&7]'
- '&7Click For'
- '&7sell item'
- '&7in this Chest'

game_sell_booster:
 display_name: '&a&lSell Booster'
 item: CHEST
 item_name: '&a&lSell Booster &7(Right-Click)'
 lore:
 - '&7You will receive more money'
 - '&7from selling items.'
 - ''
 - '&a&lMultiplier:&f x%multiplier%'
 - '&a&lDuration:&f %minutes%m (%seconds%s)'
 time: 60
 boost%: 2.0
 prize: 10000